version: '3.9'

services:

  linkerd:
    image: buoyantio/linkerd:1.7.5

    ports:
    - "8080:8080"
    - "9990:9990"
    # we must mount the config file and the disco directory
    volumes:
    - ./config.yaml:/config.yaml
    - ./disco:/io.buoyant/disco
    command: /config.yaml
