version: "3.9"

services:
  kong-database:
    image: postgres:13
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 3s
      retries: 5

  kong-migrations:
    image: kong:3.6
    depends_on:
      kong-database:
        condition: service_healthy
    command: ["kong", "migrations", "bootstrap"]
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong

  kong:
    image: kong:3.6
    depends_on:
      kong-migrations:
        condition: service_completed_successfully
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "8000:8000"
      - "8001:8001"

  service1:
    build:
      context: ./services/service1
    
    volumes:
      - ./services/service1:/usr/src/core      # mount code for live reload
    command: >
      fastapi dev --host 0.0.0.0 --port 8000
    ports:
      - "9001:8000"
    expose:
      - 8000

  service2:
    build:
      context: ./services/service2
    volumes:
      - ./services/service2:/usr/src/core      # mount code for live reload
    command: >
      fastapi dev --host 0.0.0.0 --port 8000
    ports:
      - "9002:8000"
    expose:
      - 8000
